### ISSUE TITLE
image not send error

### ISSUE THREAD

**Issue by davinderSingh1** [dimaskiddo/go-whatsapp-multidevice-rest#11]
image file not send 

![Cadapture](https://user-images.githubusercontent.com/78996662/167301567-2c1eee85-7517-4b77-82ee-11fa482f9c83.PNG)

**Comment by dimaskiddo** [comment]
MSISDN should be reconstructed but suggested not using @s.whatsapp.net
Please attach the logs come from the server, i can't debug it without any further information

Just see the postman posibility is the server dead by panic

**Comment by dimaskiddo** [comment]
I've been investigate this issue, it's related to use of animated webp, which currently webp library in go only can decode static webp image not animated

In current build it's should return an error of decoding WebP
This issue won't fix until further library update available for go WebP

Thank's for reporting @davinderSingh1

**Comment by Gagan1212g** [comment]
Fix ?

**Comment by dimaskiddo** [comment]
No Animated WebP Convertion support natively in Go @Gagan1212g

**Comment by Gagan1212g** [comment]
Dear .pdf sending possible ?
