### ISSUE TITLE
always lost session after restart

### ISSUE THREAD

**Issue by davinderSingh1** [dimaskiddo/go-whatsapp-multidevice-rest#13]
always lost session after restart.
re login how to fix

**Comment by dimaskiddo** [comment]
After restart if WhatsApp.db under dbs/ directory not removed it should restored Automatically
Please give more information like server logs information

**Comment by ibnux** [comment]
@davinderSingh1  to make session always resume after restart
you need create login with your whatsap phone, starting with country code

as you see when apps started, it will show phone number
<img width="373" alt="Screen Shot 2022-06-06 at 12 31 04" src="https://user-images.githubusercontent.com/811955/172101058-46a7c3d7-0f17-47f3-a640-aec0f6f57ab1.png">

it must be the same with username auth

i create Base64code for login like this

<img width="514" alt="Screen Shot 2022-06-06 at 12 32 57" src="https://user-images.githubusercontent.com/811955/172100959-ca1336d9-ce0a-405f-91b5-3bcf38c01a23.png">
