### ISSUE TITLE
how to add new session?

### ISSUE THREAD

**Issue by Cloud-Dark** [dimaskiddo/go-whatsapp-multidevice-rest#17]
i have one session, and success auth to whatsapp, but i need multiple session, and i get it when i try to add new session
![image](https://user-images.githubusercontent.com/28920412/171801334-c8a5085b-1eb5-43f3-bc75-b06e32afd95a.png)
can you help me for this? its bug? or what?

**Comment by dimaskiddo** [comment]
Multi Session/Account is splitted based on JWT Token generated when hitting /api/v1/whatsapp/auth
Where using Username with different MSISDN, it will generate new JWT Token. Use that token for sending message with new MSISDN session

**Comment by alann-maulana** [comment]
Halo mas @dimaskiddo so what about `AUTH_BASIC_USERNAME` and `AUTH_BASIC_PASSWORD` keys for? As we can use almost new username and password for authenticating? 😁
