### ISSUE TITLE
Browser icon

### ISSUE THREAD

**Issue by Diden05** [dimaskiddo/go-whatsapp-multidevice-rest#19]
Hi!
Tell me how to change the name and icon on the page of connected devices so that the client looks like a normal browser for the whatsap?
![IMG_20220611_084424](https://user-images.githubusercontent.com/1879413/173174980-25980903-8d99-447a-b02d-8cc42116efa8.jpg)

**Comment by dimaskiddo** [comment]
You can change it in

https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/blob/7142a8a1cc9173579379c0ce269ec4bff3133e1f/pkg/whatsapp/whatsapp.go#L60-L62

As it is defined in WhatsApp Proto
Currently it's not configurable yet from environment variable
