### ISSUE TITLE
unlimited JWT token, no Expired

### ISSUE THREAD

**Issue by ibnux** [dimaskiddo/go-whatsapp-multidevice-rest#2]
Feature request

if expired zero
```
AUTH_JWT_EXPIRED_HOUR=0
```

Then AUTH JWT no expired.

i use api to api to send Whatsapp Message.

if JWT expired, i need to relogin, and add new jwt to backend apps.

it can be automatically to call login, but is good if we dont need to do that  😁

**Comment by dimaskiddo** [comment]
Possible but will broke security concern hehe 😄

**Comment by dimaskiddo** [comment]
By this commit [0a53e78](https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/commit/0a53e787f907612dc7c4e0777135cda90ff33bc6) could you try to use '0' as JWT Expired Hour Pak @ibnux ?

**Comment by dimaskiddo** [comment]
By the way auto restore connection feature also has been implemented if the server restarted (startup task)

**Comment by ibnux** [comment]
No problem with security 😁 

The WA Gateway is using localhost, not exposed to iP Public.

i use PHP for frontend and connect with curl to whatsapp API 😁 

Thanks for implementing it 👍

**Comment by dimaskiddo** [comment]
Is't already tested pak? so i can close this issue hehe

**Comment by ibnux** [comment]
Yes it works

no **exp** field

<img width="1245" alt="Screen Shot 2022-04-22 at 16 13 29" src="https://user-images.githubusercontent.com/811955/164675913-cb0bb1b9-2acf-4164-900a-e1364eaed73a.png">
<img width="873" alt="Screen Shot 2022-04-22 at 16 13 42" src="https://user-images.githubusercontent.com/811955/164675931-97c0e3b9-c89d-4d7c-977e-3d4c8fe028dc.png">

**Comment by dimaskiddo** [comment]
Btw Basic Auth user is still the same pak using phone number and i think there is no more need X-JWT-Claims since now using built-in middleware from labstack/echo hehe
