### ISSUE TITLE
Missmatch Authentication and logout

### ISSUE THREAD

**Issue by ahmedRSA** [dimaskiddo/go-whatsapp-multidevice-rest#25]
POST remote_ip="127.0.0.1:50810" uri=/api/v1/whatsapp/login
INFO[2022-09-10T01:42:00+05:30] Checking WhatsApp Client for 1462465xxxx     
INFO[2022-09-10T01:42:00+05:30] Logging out WhatsApp Client for 1462465xxxx Due to Missmatch Authentication 

auto logout after 1 minute

**Comment by ahmedRSA** [comment]
Help pls?

**Comment by ahmedRSA** [comment]
Can you help

**Comment by ibnux** [comment]
Back to previous commit
i am stable at version 1.3.0

**Comment by dimaskiddo** [comment]
Hello @ahmedRSA did you use same phone number as username when generating bearer token in /auth?
in new version it verified username and registered phone number in whatsapp, when it's missmatch it will be auto logged out
