### ISSUE TITLE
missing or malformed jwt

### ISSUE THREAD

**Issue by IniAku** [dimaskiddo/go-whatsapp-multidevice-rest#27]
no matter what i do, missing or malformed jwt. Have login, and put the token as Authorization. can you help?

**Comment by dimaskiddo** [comment]
Can you give example where you put the Token?
If you use Swagger put "Bearer" in front of the JWT Token so it's looks like "Bearer <JWT Token>"

**Comment by IniAku** [comment]
curl -X 'GET' \
  'http://127.0.0.1:3000/api/v1/whatsapp/group' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXQiOnsiamlkIjoiYWRtaW4ifSwiZXhwIjoxNjY1MjA0NjAxLCJpYXQiOjE2NjUxMTgyMDF9.a-O9xZG84uDt6mbq3e-sMeXMAURkdVfPoYXRgmmOec0'

Respon Body : {
  "status": false,
  "code": 500,
  "error": "WhatsApp Client is not Valid"
}

**Comment by dimaskiddo** [comment]
Clossing this issue due to no response yet
