### ISSUE TITLE
Pre-build binary running on windows getting error WhatsApp Client is not Valid

### ISSUE THREAD

**Issue by Prathameshwar** [dimaskiddo/go-whatsapp-multidevice-rest#29]
Able to generate token and QR code but during login (scanning from WhatsApp android app) is showing error as below:

INFO[2022-12-18T12:10:00+05:30] Checking WhatsApp Client for 91981833xxxx
INFO[2022-12-18T12:10:00+05:30] Logging out WhatsApp Client for 91981833xxxx Due to Missmatch Authentication

Want to share one more information. Yesterday mobile app got updated for new WhatsApp update. Can this be a reason?

**Comment by dimaskiddo** [comment]
Make sure username that you use when generating token is the phone number, missmatch authentication caused by it

**Comment by dimaskiddo** [comment]
Clossing this issue due to inactivity
Please feel free to re-open the issue
