### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by bahkadomos** [dimaskiddo/go-whatsapp-multidevice-rest#32]
Is there a way to connect to whatsapp using a proxy? I understand that this package is a REST wrapper for whatsmeow that does not support proxies. I was thinking of setting a proxy on the system through proxyfier, setting rules on localhost and 3000 port (where the server is running), but I'm not quite sure if whatsapp requests will go through this proxy.

Of course, I can pass all traffic through the proxyfier, but I have a proxy with IP rotation by link, and if I make a request to change IP from under the same proxy, the Internet will go offline.

In general, my question is: how to set rules in proxyfier so that requests to whatsapp go through a proxy, and everything else does not. Any ideas?

**Comment by dimaskiddo** [comment]
I already push with Commit ID https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/commit/a300564b02d531ebe058c67b5902437443de001f
Maybe you can and try it in new release v1.5.1 @bahkadomos
