### ISSUE TITLE
Update latest whatsmeow?

### ISSUE THREAD

**Issue by Diden05** [dimaskiddo/go-whatsapp-multidevice-rest#33]
Latest whatsmeow required golang 1.19, any updates?

**Comment by agrogov** [comment]
Ad it would be great to actualize code for the new whatsmeow version
`Build Error: go build -o go-whatsapp-multidevice-rest/cmd/main/__debug_bin -gcflags all=-N -l .
# github.com/dimaskiddo/go-whatsapp-multidevice-rest/pkg/whatsapp
../../pkg/whatsapp/whatsapp.go:332:60: cannot use msgId (variable of type string) as type *"go.mau.fi/whatsmeow/binary/proto".Message in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:332:67: cannot use msgContent (variable of type *"go.mau.fi/whatsmeow/binary/proto".Message) as type whatsmeow.SendRequestExtra in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:374:60: cannot use msgId (variable of type string) as type *"go.mau.fi/whatsmeow/binary/proto".Message in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:374:67: cannot use msgContent (variable of type *"go.mau.fi/whatsmeow/binary/proto".Message) as type whatsmeow.SendRequestExtra in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:429:60: cannot use msgId (variable of type string) as type *"go.mau.fi/whatsmeow/binary/proto".Message in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:429:67: cannot use msgContent (variable of type *"go.mau.fi/whatsmeow/binary/proto".Message) as type whatsmeow.SendRequestExtra in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:561:60: cannot use msgId (variable of type string) as type *"go.mau.fi/whatsmeow/binary/proto".Message in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:561:67: cannot use msgContent (variable of type *"go.mau.fi/whatsmeow/binary/proto".Message) as type whatsmeow.SendRequestExtra in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:614:60: cannot use msgId (variable of type string) as type *"go.mau.fi/whatsmeow/binary/proto".Message in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:614:67: cannot use msgContent (variable of type *"go.mau.fi/whatsmeow/binary/proto".Message) as type whatsmeow.SendRequestExtra in argument to WhatsAppClient[jid].SendMessage
../../pkg/whatsapp/whatsapp.go:614:67: too many errors (exit status 2)`

**Comment by dimaskiddo** [comment]
Sorry for my inactivity and the late response, too much to do in real life 🥂 
@Diden05 @agrogov It should be done at release v1.5.0 with Commit ID [32a6540](https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/commit/32a6540a1329d8cde92a73eeb4742a5c9368ec46)
