### ISSUE TITLE
Logout after scan qrcode

### ISSUE THREAD

**Issue by devalexandre** [dimaskiddo/go-whatsapp-multidevice-rest#79]
After making a few login attempts, after scanning the QRCODE, the device is automatically disconnected, the record disappears from the database too, the old version worked, I don't understand why it stopped

![image](https://github.com/user-attachments/assets/ea31d79e-7ebe-49d8-af94-0935908c2337)

**Comment by glennprays** [comment]
i'm facing the same issue, so how to fix this problem?
