### ISSUE TITLE
[doc] API documentation

### ISSUE THREAD

**Issue by nalakawula** [dimaskiddo/go-whatsapp-multidevice-rest#9]
It is a good idea to have API documentation.

Thanks

**Comment by Gagan1212g** [comment]
Demo video how to use please sir

**Comment by nalakawula** [comment]
That sounds great, thanks @dimaskiddo

**Comment by ibnux** [comment]
@dimaskiddo how do I contribute to WIKI?

I though forking can pull to wiki but is not 😅

So I can write the docs, and you focus to code 😀

**Comment by dimaskiddo** [comment]
Pak @ibnux i already invite you as collaborators in this repo
Thank you so much for your help pak

**Comment by dimaskiddo** [comment]
Embedded Swagger is implemented by this commit [3ea0b64](https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/commit/3ea0b64602ad7ddb30487fca5d5c421f36d1de88)

Can be accessed under `127.0.0.1:3000/api/v1/whatsapp/docs/index.html`

![image](https://user-images.githubusercontent.com/21129987/167390154-27010c21-e075-4f17-989c-8fd6f92c4a7f.png)
